# Self-hosting alternative: `docker compose up -d`, then open http://localhost:8080
services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.6
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Manila
